# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twaictl < Formula
  desc "台智雲 TWCC 平台的非官方命令列工具（Unofficial CLI for Taiwan AI Cloud TWCC）"
  homepage "https://github.com/gilbertchiao/twaictl"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gilbertchiao/twaictl/releases/download/v0.3.1/twaictl_0.3.1_darwin_amd64.tar.gz"
      sha256 "a0252f392fd3fc2eb73abaa707807abefc5b67c3cdd17d9b246862a729fe5162"

      define_method(:install) do
        bin.install "twaictl"
        generate_completions_from_executable(bin/"twaictl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gilbertchiao/twaictl/releases/download/v0.3.1/twaictl_0.3.1_darwin_arm64.tar.gz"
      sha256 "8300619037c643f9e58c222da4d2e2b47d42fdca662aad45a35144b80959d5ff"

      define_method(:install) do
        bin.install "twaictl"
        generate_completions_from_executable(bin/"twaictl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gilbertchiao/twaictl/releases/download/v0.3.1/twaictl_0.3.1_linux_amd64.tar.gz"
      sha256 "b3207648b88d7317222f629f325559bd12a91887cdfc3d5da206c23170abb34f"
      define_method(:install) do
        bin.install "twaictl"
        generate_completions_from_executable(bin/"twaictl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gilbertchiao/twaictl/releases/download/v0.3.1/twaictl_0.3.1_linux_arm64.tar.gz"
      sha256 "82e71da520ea18ec342762c98b7fb840d99e611b07fdc8fabd614c7fe6d12326"
      define_method(:install) do
        bin.install "twaictl"
        generate_completions_from_executable(bin/"twaictl", "completion")
      end
    end
  end

  test do
    system "#{bin}/twaictl", "version"
  end
end
